################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_activate.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_change.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_create.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_deactivate.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_delete.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_info_get.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_initialize.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_system_activate.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_activate.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_change.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_create.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_deactivate.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_delete.c \
C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_info_get.c 

OBJS += \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_activate.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_change.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_create.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_deactivate.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_delete.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_expiration_process.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_info_get.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_initialize.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_system_activate.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_system_deactivate.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_thread_entry.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_activate.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_change.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_create.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_deactivate.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_delete.o \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_info_get.o 

C_DEPS += \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_activate.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_change.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_create.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_deactivate.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_delete.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_expiration_process.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_info_get.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_initialize.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_system_activate.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_system_deactivate.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_thread_entry.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_activate.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_change.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_create.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_deactivate.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_delete.d \
./Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_info_get.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_activate.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_activate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_activate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_change.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_change.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_change.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_create.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_create.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_create.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_deactivate.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_deactivate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_deactivate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_delete.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_delete.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_delete.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_expiration_process.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_expiration_process.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_info_get.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_info_get.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_info_get.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_initialize.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_initialize.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_initialize.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_system_activate.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_system_activate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_system_activate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_system_deactivate.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_system_deactivate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/tx_timer_thread_entry.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/tx_timer_thread_entry.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_activate.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_activate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/txe_timer_activate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_change.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_change.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/txe_timer_change.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_create.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_create.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/txe_timer_create.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_deactivate.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_deactivate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/txe_timer_deactivate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_delete.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_delete.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/txe_timer_delete.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/ThreadX/SW\ timers/Default/txe_timer_info_get.o: C:/Users/T3S\ Solutions\ Ltd/source/repos/sjscymru/stm32/x-cube-azrtos-h7/Middlewares/ST/threadx/common/src/txe_timer_info_get.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DTX_INCLUDE_USER_DEFINE_FILE -DSTM32H743xx -c -I../../Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc -I../../../../../../../Drivers/BSP/STM32H735G-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/ThreadX/RTOS/ThreadX/SW timers/Default/txe_timer_info_get.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

